### ISSUE TITLE
add RISC-V architecture support

### ISSUE THREAD

**Issue by frantony** [embox/embox#1047] opened 2017-03-03 08:17 UTC
[RISC-V](https://www.riscv.org) is a new and very promising  open instruction set architecture.

**Comment by kandeshvari** [comment] 2018-10-03 08:07
Are there public MCs or CPUs available?

**Comment by frantony** [comment] 2018-10-03 08:30
There is a RISCV32 [HiFive1 board](https://www.sifive.com/boards/hifive1).
For RISCV64 please see [HiFive Unleashed board](https://www.crowdsupply.com/sifive/hifive-unleashed).

You can use mainline qemu for HiFive board emulation.

**Comment by kandeshvari** [comment] 2018-10-11 07:46
1. What arch is better to get as a base for porting? Is `generic` a stub for any new arch? 
2. What other code I have to write besides `src/arch`?

**Comment by kandeshvari** [comment] 2018-12-17 15:03
I'm trying to build minimal kernel as it described [here](http://web.archive.org/web/20160105032147/https://code.google.com/p/embox/wiki/EmboxArchPorting)

my template:
```
package genconfig

configuration conf {
	@Runlevel(2) include embox.arch.riscv.kernel.boot
	@Runlevel(2) include embox.arch.riscv.kernel.arch
	@Runlevel(2) include embox.arch.system(core_freq=3200000000)

	@Runlevel(2) include embox.kernel.spinlock(spin_debug=false)
	@Runlevel(2) include embox.driver.serial.sifive_uart(base_addr=0x10013000,baud_rate=115200,clock_freq=32000000)
	@Runlevel(2) include embox.driver.diag(impl="embox__driver__serial__sifive_uart")
	@Runlevel(2) include embox.driver.interrupt.no_interrupts
}
```
next:
```
make confload-riscv/qemu-sifive-e
make
```

but gain an error: 
```
In file included from src/s_fma.c:31:0:
/home/dk/devel/other/embox/build/extbld/third_party/lib/OpenLibm/openlibm-2252cbd02c176a31f74fa10f8fcdf926c3124987/include/openlibm_fenv.h:16:2: error: #error "Unsupported platform"
```

Do I really need libm for minimal kernel? How to switch it's build off?

**Comment by alexkalmuk** [comment] 2018-12-17 16:14
@kandeshvari Probably, you can try `include embox.compat.libc.math_libm_none`

**Comment by anton-bondarev** [comment] 2018-12-18 10:33
@kandeshvari And use add line
	`include embox.compat.libc.stdio.print(support_floating=0)`

for switch off  floating point support in 'print' routines

**Comment by anton-bondarev** [comment] 2018-12-18 10:37
@kandeshvari 

> Probably, you can try include embox.compat.libc.math_libm_none

try to use `include embox.compat.libc.math_builtins`

**Comment by nastya-nizharadze** [comment] 2019-09-20 12:22
Hi, **@kandeshvari**
I'm going to continue porting Embox to RISC-V architecture. It would be great if you could tell me what results have already been achieved.

**Comment by kandeshvari** [comment] 2019-09-20 12:36
Hi @nastya-nizharadze 

Plz see in https://github.com/kandeshvari/embox/tree/risc-v-support

I've done early stage with qemu-sifive-e
I've added boot code and diag_serial via sifive's uart. It boots now and shows
```

Embox kernel start
runlevel: init level is 0
runlevel: init level is 1
	unit: initializing embox.driver.clock.clint_timer: CPU frequency: 16000000
done
runlevel: init level is 2
runlevel: init level is 3
runlevel: init level is 4
```

Next I started interrupts but switched to other private tasks and abandoned this one :(

some hints to help:

## compile risc-v qemu
	./configure --target-list=riscv32-softmmu,riscv64-softmmu --extra-cflags="-std=gnu99"
	make -j 4

## risc-v baremetal examples

	https://github.com/michaeljclark/riscv-probe

## disasm
	# show symbols
	objdump --syms label-test.o
	riscv32-unknown-elf-objdump -d build/base/bin/embox | less

## qemu gdb
	# terminate qemu -> CTRL-A, X
	qemu-system-riscv32 -nographic -machine sifive_e -kernel build/base/bin/embox -s -S
	riscv32-unknown-elf-gdb -x gdb.script ./hello-bare-c

	$ cat gdb.script 
	target remote localhost:1234

Good luck!

**Comment by kandeshvari** [comment] 2019-09-20 12:39
more notes:

## resources

	[Tuesday @ 0900 RISC V Interrupts Krste Asanović, UC Berkeley & SiFive Inc](https://www.youtube.com/watch?v=iPbaG_wnNJY)

### interrupts
	[FE310G: an open source RISC-V microcontroller – Interrupt System](http://embeddedsystems.io/fe310g-open-source-riscv-microcontroller-interrupt-system/)

https://www.sifive.com/blog/all-aboard-part-3-linker-relaxation-in-riscv-toolchain

**Comment by nastya-nizharadze** [comment] 2019-09-20 12:43
Thank you very much, @kandeshvari !

**Comment by anton-bondarev** [comment] 2019-09-23 07:56
Hi @kandeshvari!

> Plz see in https://github.com/kandeshvari/embox/tree/risc-v-support
> 
> I've done early stage with qemu-sifive-e
> I've added boot code and diag_serial via sifive's uart. It boots now and shows

Looks great. Thank you. May you create PR for your current achievements?

**Comment by kandeshvari** [comment] 2019-09-23 16:14
@anton-bondarev, 
sure, give me few days to prepare PR.

**Comment by kandeshvari** [comment] 2019-09-24 12:54
@anton-bondarev, 
need help ;) 
embox/src/compat/libc/include/inttypes.h:192 - how these defines were constructed? I can't find __e2k__ or __mips__ in code

**Comment by anton-bondarev** [comment] 2019-09-24 13:34
@kandeshvari 
Do you mean 
`#if defined (__e2k__) || (defined(__mips__) && !defined(__gnu_linux__)) || defined(__sparc__) || defined(__microblaze__) || defined(__PPC__)`
?

These macros ` _e2k_` or `__PPC__` predefined in cross-compilers (`<arch>-gcc`) . We check type of architecture for defining some integer types. It's may be different for different cross-compilers for the same arch. MIPS for example:
`(defined(__mips__) && !defined(__gnu_linux__)) `
and
`(defined(__mips__) && defined(__gnu_linux__))`
in line 212

In the first case we use mips-elf-gcc from own build [https://github.com/embox/crosstool]( https://github.com/embox/crosstool) In the other case we use mips-linux-gcc from debian repository.

I think for risc-v you should print the predefined macros from your gcc [https://stackoverflow.com/questions/2224334/gcc-dump-preprocessor-defines](https://stackoverflow.com/questions/2224334/gcc-dump-preprocessor-defines)
And add to appropriate `#if #else` branch it depends of uint32_t and other types declarations

**Comment by kandeshvari** [comment] 2019-09-24 18:44
@anton-bondarev,
yes, it is! Thank you for hint! I've solved this step, but, it's a kind of magic, my branch does not compile now. It is strange, because I built it few month ago. Now I'm getting an error:

```
In file included from src/kernel/thread/signal/siginfoq.c:17:
./src/include/mem/objalloc.h:27:10: fatal error: module/embox/mem/objalloc.h: No such file or directory
 #include <module/embox/mem/objalloc.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I suppose this is a build system's error - some modules were included implicitly. Could you tell me how to get dependency graph for all modules? Or maybe you know what module needs to be included/excluded/replaced?

**Comment by kandeshvari** [comment] 2019-09-25 15:16
I've removed `embox.driver.clock.clint_timer` from PR due to `jiffles_init()` has added to `clock_source.c`. `jiffles_init()` needs to use interrupt timer that I don't have at the moment. I only started to add interrupts and tried to use hz clock_source that can't be used now.

**Comment by anton-bondarev** [comment] 2019-09-26 08:05
> I've removed embox.driver.clock.clint_timer from PR

Not a problem.

Thanks a lot for your work! PR will be merged soon!

**Comment by anton-bondarev** [comment] 2021-02-25 08:44
Now Embox has support for several RISC-V platforms. therefore the issue is closed. It will open new issues for others RISC-V features

**Closed by anton-bondarev** 2021-02-25 08:44 UTC
Labels: arch:risc-v, porting
